package handler

import (
	"context"
	"net/http"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"

	"github.com/dboarif/payment-sandbox/internal/constant"
	"github.com/dboarif/payment-sandbox/internal/model"
	"github.com/dboarif/payment-sandbox/internal/pkg/apperror"
	"github.com/dboarif/payment-sandbox/internal/repository"
	"github.com/dboarif/payment-sandbox/internal/service"
)

func futureDate() string { return time.Now().Add(48 * time.Hour).UTC().Format(time.RFC3339) }

func validInvoiceBody() map[string]any {
	return map[string]any{
		"customer_name": "Budi",
		"amount":        50000,
		"due_date":      futureDate(),
		"description":   "Order #1",
	}
}

// SRS §2.3: creating an invoice yields a unique number and a payment link.
func TestCreateInvoice_ReturnsNumberAndPaymentLink(t *testing.T) {
	e := newTestEnv()
	uid, bearer := e.tokenFor(t, constant.RoleMerchant)

	rec := e.do(t, http.MethodPost, "/api/v1/invoices", bearer, validInvoiceBody())

	assertStatus(t, rec, http.StatusCreated)

	var body model.InvoiceResponse
	decode(t, rec, &body)
	if body.InvoiceNumber == "" {
		t.Error("invoice_number must be generated by the system")
	}
	if body.PaymentToken == "" {
		t.Error("payment_token must be generated by the system")
	}
	if body.Status != string(constant.InvoicePending) {
		t.Errorf("status = %q, want PENDING", body.Status)
	}
	// SRS §2.3: the payment link must be built from the token so the merchant can share it.
	if want := "/api/v1/pay/" + body.PaymentToken; body.PaymentLink != want {
		t.Errorf("payment_link = %q, want %q", body.PaymentLink, want)
	}
	// Ownership is derived from the token, not the payload.
	if e.invoice.lastInput.MerchantID != uid {
		t.Errorf("merchant id = %s, want the token subject %s", e.invoice.lastInput.MerchantID, uid)
	}
	if e.invoice.lastInput.Amount != 50000 {
		t.Errorf("amount = %d, want 50000", e.invoice.lastInput.Amount)
	}
}

// A client must not be able to claim an invoice on behalf of another merchant.
func TestCreateInvoice_IgnoresClientSuppliedMerchantID(t *testing.T) {
	e := newTestEnv()
	uid, bearer := e.tokenFor(t, constant.RoleMerchant)

	body := validInvoiceBody()
	body["merchant_id"] = uuid.New().String() // attacker-supplied
	body["status"] = "PAID"                   // attacker-supplied

	rec := e.do(t, http.MethodPost, "/api/v1/invoices", bearer, body)

	assertStatus(t, rec, http.StatusCreated)
	if e.invoice.lastInput.MerchantID != uid {
		t.Errorf("merchant id = %s, want the token subject %s", e.invoice.lastInput.MerchantID, uid)
	}

	var resp model.InvoiceResponse
	decode(t, rec, &resp)
	if resp.Status != string(constant.InvoicePending) {
		t.Errorf("status = %q — a client must not be able to create an already-PAID invoice", resp.Status)
	}
}

// SRS §4.5: amount > 0, valid email, and required fields.
func TestCreateInvoice_ValidationErrors(t *testing.T) {
	cases := []struct {
		name   string
		mutate func(m map[string]any)
	}{
		{"zero amount", func(m map[string]any) { m["amount"] = 0 }},
		{"negative amount", func(m map[string]any) { m["amount"] = -1 }},
		{"missing amount", func(m map[string]any) { delete(m, "amount") }},
		{"missing customer name", func(m map[string]any) { delete(m, "customer_name") }},
		{"empty customer name", func(m map[string]any) { m["customer_name"] = "" }},
		{"missing due date", func(m map[string]any) { delete(m, "due_date") }},
		{"unparseable due date", func(m map[string]any) { m["due_date"] = "31-12-2030" }},
		{"malformed customer email", func(m map[string]any) { m["customer_email"] = "not-an-email" }},
		{"description too long", func(m map[string]any) { m["description"] = strings.Repeat("x", 501) }},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			e := newTestEnv()
			_, bearer := e.tokenFor(t, constant.RoleMerchant)

			body := validInvoiceBody()
			tc.mutate(body)

			rec := e.do(t, http.MethodPost, "/api/v1/invoices", bearer, body)
			assertStatus(t, rec, http.StatusBadRequest)
		})
	}
}

// SRS §4.5: due date must not be in the past — enforced in the service.
func TestCreateInvoice_PastDueDateRejected(t *testing.T) {
	e := newTestEnv()
	_, bearer := e.tokenFor(t, constant.RoleMerchant)
	e.invoice.createFn = func(context.Context, service.CreateInvoiceInput) (*model.Invoice, error) {
		return nil, apperror.New(apperror.KindBadRequest, "INVALID_DUE_DATE", "due_date must be in the future")
	}

	body := validInvoiceBody()
	body["due_date"] = time.Now().Add(-24 * time.Hour).UTC().Format(time.RFC3339)

	rec := e.do(t, http.MethodPost, "/api/v1/invoices", bearer, body)

	assertStatus(t, rec, http.StatusBadRequest)
	if code := errCode(t, rec); code != "INVALID_DUE_DATE" {
		t.Errorf("error code = %q, want INVALID_DUE_DATE", code)
	}
}

func TestCreateInvoice_RequiresMerchantRole(t *testing.T) {
	e := newTestEnv()
	_, bearer := e.tokenFor(t, constant.RoleAdmin)

	rec := e.do(t, http.MethodPost, "/api/v1/invoices", bearer, validInvoiceBody())
	assertStatus(t, rec, http.StatusForbidden)
}

func TestCreateInvoice_RequiresAuth(t *testing.T) {
	e := newTestEnv()
	rec := e.do(t, http.MethodPost, "/api/v1/invoices", "", validInvoiceBody())
	assertStatus(t, rec, http.StatusUnauthorized)
}

// ── list ──────────────────────────────────────────────────────────────────────

// SRS §2.3: list is filterable and always scoped to the caller.
func TestListInvoices_ForwardsFiltersAndScopesToOwner(t *testing.T) {
	e := newTestEnv()
	uid, bearer := e.tokenFor(t, constant.RoleMerchant)

	from := "2026-01-01T00:00:00Z"
	to := "2026-12-31T23:59:59Z"
	rec := e.do(t, http.MethodGet,
		"/api/v1/invoices?status=PAID&from="+from+"&to="+to+"&page=3&page_size=10", bearer, nil)

	assertStatus(t, rec, http.StatusOK)

	f := e.invoice.lastFilter
	if f.MerchantID == nil || *f.MerchantID != uid {
		t.Errorf("list not scoped to the caller: %v", f.MerchantID)
	}
	if f.Status == nil || *f.Status != constant.InvoicePaid {
		t.Errorf("status filter = %v, want PAID", f.Status)
	}
	if f.From == nil || f.From.Format(time.RFC3339) != from {
		t.Errorf("from = %v, want %s", f.From, from)
	}
	if f.To == nil || f.To.Format(time.RFC3339) != to {
		t.Errorf("to = %v, want %s", f.To, to)
	}
	if e.invoice.lastOffset != 20 || e.invoice.lastLimit != 10 {
		t.Errorf("offset/limit = %d/%d, want 20/10", e.invoice.lastOffset, e.invoice.lastLimit)
	}
}

// A bogus status must be rejected rather than silently returning nothing.
func TestListInvoices_RejectsUnknownStatus(t *testing.T) {
	e := newTestEnv()
	_, bearer := e.tokenFor(t, constant.RoleMerchant)

	rec := e.do(t, http.MethodGet, "/api/v1/invoices?status=CANCELLED", bearer, nil)

	assertStatus(t, rec, http.StatusBadRequest)
	if code := errCode(t, rec); code != "INVALID_STATUS" {
		t.Errorf("error code = %q, want INVALID_STATUS", code)
	}
}

func TestListInvoices_RejectsMalformedDates(t *testing.T) {
	for _, q := range []string{"from=yesterday", "to=2026-13-45", "from=1700000000"} {
		t.Run(q, func(t *testing.T) {
			e := newTestEnv()
			_, bearer := e.tokenFor(t, constant.RoleMerchant)

			rec := e.do(t, http.MethodGet, "/api/v1/invoices?"+q, bearer, nil)
			assertStatus(t, rec, http.StatusBadRequest)
			if code := errCode(t, rec); code != "INVALID_DATE" {
				t.Errorf("error code = %q, want INVALID_DATE", code)
			}
		})
	}
}

// SRS §3.2: page size is capped so a client cannot ask for the whole table.
func TestListInvoices_PageSizeIsCapped(t *testing.T) {
	e := newTestEnv()
	_, bearer := e.tokenFor(t, constant.RoleMerchant)

	rec := e.do(t, http.MethodGet, "/api/v1/invoices?page_size=100000", bearer, nil)

	assertStatus(t, rec, http.StatusOK)
	if e.invoice.lastLimit != 100 {
		t.Errorf("limit = %d, want it capped at 100", e.invoice.lastLimit)
	}
}

func TestListInvoices_DefaultPagination(t *testing.T) {
	e := newTestEnv()
	_, bearer := e.tokenFor(t, constant.RoleMerchant)

	rec := e.do(t, http.MethodGet, "/api/v1/invoices", bearer, nil)

	assertStatus(t, rec, http.StatusOK)
	if e.invoice.lastOffset != 0 || e.invoice.lastLimit != 20 {
		t.Errorf("offset/limit = %d/%d, want 0/20", e.invoice.lastOffset, e.invoice.lastLimit)
	}
}

func TestListInvoices_ItemsCarryPaymentLink(t *testing.T) {
	e := newTestEnv()
	uid, bearer := e.tokenFor(t, constant.RoleMerchant)

	e.invoice.listFn = func(context.Context, repository.InvoiceFilter, int, int) ([]model.Invoice, int64, error) {
		return []model.Invoice{{
			ID: uuid.New(), InvoiceNumber: "INV-1", MerchantID: uid, Amount: 1000,
			Status: constant.InvoicePending, PaymentToken: "tok-1",
		}}, 1, nil
	}

	rec := e.do(t, http.MethodGet, "/api/v1/invoices", bearer, nil)

	assertStatus(t, rec, http.StatusOK)
	var body struct {
		Data []model.InvoiceResponse `json:"data"`
	}
	decode(t, rec, &body)
	if len(body.Data) != 1 {
		t.Fatalf("data length = %d, want 1", len(body.Data))
	}
	if body.Data[0].PaymentLink != "/api/v1/pay/tok-1" {
		t.Errorf("payment_link = %q", body.Data[0].PaymentLink)
	}
}

// ── detail ────────────────────────────────────────────────────────────────────

func TestGetInvoice_OK(t *testing.T) {
	e := newTestEnv()
	_, bearer := e.tokenFor(t, constant.RoleMerchant)
	id := uuid.New()

	rec := e.do(t, http.MethodGet, "/api/v1/invoices/"+id.String(), bearer, nil)

	assertStatus(t, rec, http.StatusOK)
	var body model.InvoiceResponse
	decode(t, rec, &body)
	if body.ID != id.String() {
		t.Errorf("id = %q, want %q", body.ID, id)
	}
}

// SRS §2.3: a merchant must not be able to read another merchant's invoice.
func TestGetInvoice_ForeignInvoiceIsForbidden(t *testing.T) {
	e := newTestEnv()
	_, bearer := e.tokenFor(t, constant.RoleMerchant)
	e.invoice.getFn = func(context.Context, uuid.UUID, uuid.UUID) (*model.Invoice, error) {
		return nil, apperror.ErrForbidden
	}

	rec := e.do(t, http.MethodGet, "/api/v1/invoices/"+uuid.New().String(), bearer, nil)

	assertStatus(t, rec, http.StatusForbidden)
	if code := errCode(t, rec); code != "FORBIDDEN" {
		t.Errorf("error code = %q, want FORBIDDEN", code)
	}
}

func TestGetInvoice_NotFound(t *testing.T) {
	e := newTestEnv()
	_, bearer := e.tokenFor(t, constant.RoleMerchant)
	e.invoice.getFn = func(context.Context, uuid.UUID, uuid.UUID) (*model.Invoice, error) {
		return nil, apperror.ErrNotFound
	}

	rec := e.do(t, http.MethodGet, "/api/v1/invoices/"+uuid.New().String(), bearer, nil)
	assertStatus(t, rec, http.StatusNotFound)
}

func TestGetInvoice_RejectsMalformedID(t *testing.T) {
	e := newTestEnv()
	_, bearer := e.tokenFor(t, constant.RoleMerchant)

	rec := e.do(t, http.MethodGet, "/api/v1/invoices/12345", bearer, nil)

	assertStatus(t, rec, http.StatusBadRequest)
	if code := errCode(t, rec); code != "INVALID_ID" {
		t.Errorf("error code = %q, want INVALID_ID", code)
	}
}
